feedbacks/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^record/$', views.list_records, name='feedbacks.list_records'),
    url(r'^behavior/(?P<behavior>\w+)/$', views.list_behavior, name='feedbacks.list_behavior'),
    url(r'^behavior/(?P<behavior>\w+)/lecture/(?P<lecture_id>[0-9]+)/add$', views.add_behavior, name='feedbacks.add_behavior'),
    url(r'^behavior/(?P<behavior_id>[0-9]+)/delete$', views.delete_behavior, name='feedbacks.delete_behavior_by_id'),
    url(r'^behavior/(?P<behavior>\w+)/delete$', views.delete_behavior, name='feedbacks.delete_behavior_by_name'),
    url(r'^comment/user/$', views.list_user_comments, name='feedbacks.list_user_comments'),
    url(r'^comment/lecture/(?P<lecture_id>[0-9]+)/$', views.list_lecture_comments, name='feedbacks.list_lecture_comments'),
    url(r'^comment/lecture/(?P<lecture_id>[0-9]+)/add$', views.add_comment, name='feedbacks.add_comment'),
    url(r'^question/user/$', views.list_questions, name='feedbacks.list_user_questions'),
    url(r'^question/lecture/(?P<lecture_id>[0-9]+)/$', views.list_questions, name='feedbacks.list_lecture_questions'),
    url(r'^question/lecture/(?P<lecture_id>[0-9]+)/add$', views.add_question, name='feedbacks.add_question'),
]

nfe/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='lectures.list_categories', permanent=True), name='root'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^feedbacks/', include('feedbacks.urls')),
    url(r'^lectures/', include('lectures.urls')),
    url(r'^live/', include('live.urls')),
    url(r'^profiles/', include('profiles.urls')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feedbacks/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as _

from accounts.models import User
from lectures.models import Lecture


class Comment(models.Model):
    score = models.PositiveSmallIntegerField(_('Score'))
    detail = models.CharField(_('Detail'), max_length=200, blank=True)
    time = models.DateTimeField(_('Time'))
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    lecture = models.ForeignKey(Lecture, on_delete=models.CASCADE)
    is_visible = models.BooleanField(_('Is Visible'), default=True)

    class Meta:
        unique_together = ("user", "lecture")
        verbose_name = _('Comment')
        verbose_name_plural = _('Comment')

    def __unicode__(self):
        return '{user} - comment'.format(user=self.user)


class Question(models.Model):
    detail = models.CharField(_('Detail'), max_length=200)
    time = models.DateTimeField(_('Time'))
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    lecture = models.ForeignKey(Lecture, on_delete=models.CASCADE)
    is_visible = models.BooleanField(_('Is Visible'), default=True)

    class Meta:
        verbose_name = _('Question')
        verbose_name_plural = _('Question')

    def __unicode__(self):
        return '{user} - question'.format(user=self.user)


BEHAVIOR_CHOICES = (
    ('hide', _('Hidden')),
    ('favour', _('Favourite')),
    ('listened', _('Listened')),
)


class Behavior(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    lecture = models.ForeignKey(Lecture, on_delete=models.CASCADE)
    time = models.DateTimeField(_('Time'))
    behavior = models.CharField(
        _('Behavior'),
        max_length=12,
        choices=BEHAVIOR_CHOICES,
    )
    is_visible = models.BooleanField(_('Is Visible'), default=True)

    class Meta:
        index_together = ['user', 'behavior', 'is_visible']
        unique_together = ('user', 'lecture', 'behavior')
        verbose_name = _('Behavior')
        verbose_name_plural = _('Behavior')

    def __unicode__(self):
        return '{user} - {b}'.format(user=self.user, b=self.behavior)

feedbacks/forms.py
from django.forms import ModelForm
from .models import Comment

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['score', 'detail']

feedbacks/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.utils import timezone
from django.urls import reverse
from django.db import IntegrityError
from django.http import Http404, JsonResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required

from .models import (
    Comment,
    Question,
    Behavior,
    BEHAVIOR_CHOICES
)
from accounts.models import User
from lectures.models import Lecture


def list_records(request):
    user = request.user
    record_list = []
    if user.is_authenticated:
        record_list = Behavior.objects.filter(user__id=request.user.id, behavior='listened', is_visible=True).order_by('-time')[:10]
    context = {'user': user, 'record_list': record_list}
    return render(request, 'records/records.html', context)


@login_required
def list_behavior(request, behavior):
    behavior_dict = {b[0]:b[1] for b in BEHAVIOR_CHOICES}
    if behavior not in behavior_dict:
        raise Http404("{b} behavior list does not exist.".format(b=behavior))

    behavior_name = behavior_dict["{}".format(behavior)]

    behavior_qs = Behavior.objects.filter(user__id=request.user.id, behavior=behavior, is_visible=True)
    behavior_list = behavior_qs.order_by('-time')

    context = {'behavior': behavior, 'behavior_name': behavior_name, 'behavior_list': behavior_list}
    return render(request, 'feedbacks/behaviors.html', context)


@login_required
def add_behavior(request, behavior, lecture_id):
    behavior_dict = {b[0]:b[1] for b in BEHAVIOR_CHOICES}
    if behavior not in behavior_dict:
        raise Http404("{b} behavior does not exist.".format(b=behavior))

    user = get_object_or_404(User, id=request.user.id)
    lecture = get_object_or_404(Lecture, id=lecture_id)
    time = timezone.now()
    Behavior.objects.update_or_create(user=user,
                                      lecture=lecture, behavior=behavior,
                                      defaults={'is_visible': True, 'time': time})
    return JsonResponse({'status': '200'})


@login_required
def delete_behavior(request, behavior_id=None, behavior=None):
    if behavior:
        behavior_dict = {b[0]:b[1] for b in BEHAVIOR_CHOICES}
        if behavior not in behavior_dict:
            raise Http404("{b} behavior does not exist.".format(b=behavior))

        behavior = Behavior.objects.filter(user__id=request.user.id, behavior=behavior, is_visible=True)
        behavior.update(is_visible = False)
    if behavior_id:
        behavior = get_object_or_404(Behavior, pk=behavior_id, user__id=request.user.id)
        behavior.is_visible = False
        behavior.save()
    return JsonResponse({'status': '200'})

def list_lecture_comments(request, lecture_id=None):
    comment_qs = Comment.objects.filter(lecture__id=lecture_id, is_visible=True).order_by('-time')
    context = {'lecture_id': lecture_id, 'comment_list': comment_qs}

    user = request.user
    if user.is_authenticated and user.has_perm('feedbacks.add_comment') and not comment_qs.filter(user=user):
        context['can_add_comment'] = True
    return render(request, 'feedbacks/comments.html', context)


@login_required
def list_user_comments(request):
    comment_list = Comment.objects.filter(user__id=request.user.id, is_visible=True).order_by('-time')
    context = {'comment_list': comment_list}
    return render(request, 'feedbacks/user_comments.html', context)


@login_required
def add_comment(request, lecture_id):
    if not request.user.has_perm('feedbacks.add_comment'):
        return HttpResponseRedirect(reverse('root'))
    if request.method == 'POST':
        score = request.POST['score']
        detail = request.POST['detail']
        time = timezone.now()
        user = get_object_or_404(User, id=request.user.id)
        lecture = get_object_or_404(Lecture, id=lecture_id)
        try:
            Comment.objects.create(score=score, detail=detail, time=time, user=user, lecture=lecture)
        except IntegrityError:
            return HttpResponseRedirect(reverse('root'))
        return HttpResponseRedirect(reverse('lectures.lecture_detail', args=[lecture_id]))
    else:
        lecture = get_object_or_404(Lecture, id=lecture_id)
        context = {'lecture': lecture}
        return render(request, 'feedbacks/comment.html', context)


@login_required
def list_questions(request, lecture_id=None):
    if lecture_id:
        question_qs = Question.objects.filter(lecture__id=lecture_id)
    else:
        question_qs = Question.objects.filter(user__id=request.user.id)
    question_list = question_qs.order_by('-time')
    context = {'lecture_id': lecture_id, 'question_list': question_list}
    return render(request, 'feedbacks/user_questions.html', context)


@login_required
def add_question(request, lecture_id):
    if request.method == 'POST':
        detail = request.POST['detail']
        time = timezone.now()
        user = get_object_or_404(User, id=request.user.id)
        lecture = get_object_or_404(Lecture, id=lecture_id)
        Question.objects.create(detail=detail, time=time, user=user, lecture=lecture)
        return HttpResponseRedirect(reverse('lectures.lecture_detail', args=[lecture_id]))
    else:
        lecture = get_object_or_404(Lecture, id=lecture_id)
        context = {'lecture': lecture}
        return render(request, 'feedbacks/question.html', context)

templates/feedbacks/behaviors.html
{% extends "./index.html" %}
{% load i18n %}
{% block title %}{{ behavior_name }}{% trans " Records" %}{% endblock title %}
{% block content %}
<div class="weui-panel weui-panel_access">
  <div class="weui-panel__bd">
  {% for behavior in behavior_list %}
  <div class="weui-cell weui-cell_access" id="{{ behavior.id }}" title="{{ behavior.lecture.id }}">
      <div class="weui-cell__hd"><img src="{{ MEDIA_URL }}{{ behavior.lecture.speaker.picture }}" alt="" style="width:20px;margin-right:5px;display:block"></div>
      <div class="weui-cell__bd weui-cell_primary">
        <p>
        {% blocktrans with number=behavior.lecture.meeting.number speaker_name=behavior.lecture.speaker.name %}
        The {{ number }} Meeting: {{ speaker_name }}, {% endblocktrans %}{{ behavior.lecture.topic }}
        </p>
      </div>
    </div>
  {% empty %}
  {% endfor %}
  </div>
</div>
{% endblock content %}
{% block js %}
{{ block.super }}
<script>
$(".weui-cell").bind("click", function() {
  var behavior = this
  weui.actionSheet([
    {
      label: "{% trans "View Lecture Detail" %}",
      onClick: function() {
        let url = "{% url 'lectures.lecture_detail' 0 %}".replace("0", behavior.title);
        window.location.replace(url);
      }
    },
    {
      label: "{% trans "Delete This" %}",
      onClick: function() {
        let url = "{% url 'feedbacks.delete_behavior_by_id' 0 %}".replace("0", behavior.id);
        $.get(
          url,
          function(data){
            if (data["status"] === "200"){
              $(behavior).hide();
            } else {
            }
          },
          "json"
        );
      }
    },
    {
      label: "{% trans "Delete All" %}",
      onClick: function() {
        let url = "{% url 'feedbacks.delete_behavior_by_name' 0 %}".replace("0", "{{ behavior }}");
        $.get(
          url,
          function(data){
            if (data["status"] === "200"){
              $(".weui-cell").hide();
            } else {
            }
          },
          "json"
        );
      }
    }
  ], [
    {
      label: "{% trans "Cancel" %}",
      onClick: function() {
      }
    }
  ]);
});
</script>
{% endblock js %}

templates/feedbacks/comment.html
{% extends "./index.html" %}
{% load i18n %}
{% block title %}{% trans "Add Comment" %}{% endblock title %}

{% block css %}
{{ block.super }}
<style>
#submit-btn {
  border-radius: 0px;
  width: 100%;
}
#submit-btn:after {
  border: 0px;
  border-radius: 0px;
}
</style>
{% endblock css %}

{% block content %}
{% include "./common.html" %}
<form action="{% url 'feedbacks.add_comment' lecture.id %}" method="post">
  <div class="weui-panel">
    <div class="weui-panel__bd">
      {% csrf_token %}
      <div class="weui-cell weui-cell_vcode">
        <div class="weui-cell__hd">
          <label class="weui-label">{% trans "Scored: " %}</label>
        </div>
        <div class="weui-cell__bd">
          <input class="weui-input" type="number" name="score" id="id_score" min="0" max="5" value="5" required readonly>
        </div>
        <div class="weui-cell__ft">
          <a href="javascript:;" class="weui-vcode-btn" id="score-btn">{% trans "Click to Score" %}</a>
        </div>
      </div>
      <div class="weui-cell">
        <div class="weui-cell__bd">
          <textarea class="weui-textarea" placeholder="{% trans "Please enter your comment: " %}" rows="15" name="detail" id="id_detail" maxlength="200" required></textarea>
        </div>
      </div>
    </div>
  </div>
  <div class="weui-tabbar">
    <input type="submit" class="weui-btn weui-btn_primary" id="submit-btn">
  </div>
</form>
{% endblock content %}

{% block tabbar %}
{% endblock tabbar %}

{% block js %}
{{ block.super }}
<script>
$("#score-btn").click(function(){
  weui.picker([
    {
      label: '{% trans "Soso" %}',
      value: 3,
    },
    {
      label: '{% trans "Good" %}',
      value: 5
    },
  ], {
    defaultValue: [5],
    onChange: function (result) {
      $("#id_score").attr("value", result[0].value);
    },
    onConfirm: function (result) {
      $("#id_score").attr("value", result[0].value);
    },
    id: 'singleLinePicker'
  });
});
$("form").submit(function(){
  weui.toast("{% trans "Submit Success!" %}", 500);
});
</script>
{% endblock js %}

templates/feedbacks/comments.html
{% load i18n %}
{% if can_add_comment %}
<a class="weui-cell weui-cell_access" href="{% url 'feedbacks.add_comment' lecture_id %}">
  <div class="weui-cell__bd"></div>
  <div class="weui-cell__ft">{% trans "Add Comment" %}</div>
</a>
{% endif %}
<div class="weui-cell" style="padding: 0px;"></div>
{% if comment_list %}
<div class="weui-panel">
  {% for comment in comment_list %}
  <div class="weui-panel__bd">
    <div class="weui-media-box weui-media-box_small-appmsg">
      <div class="weui-cells">
        <div class="weui-cell">
          <div class="weui-cell__hd"><img src="{{ comment.user.headimgurl }}" alt="" style="width:20px;margin-right:5px;display:block"></div>
          <div class="weui-cell__bd">
            <p style="font-size: 14px;">{{ comment.user.last_name }}{{ comment.user.first_name }}({{ comment.user.company }})</p>
          </div>
          <span class="weui-cell__ft" style="font-size: 13px;">{{ comment.score }} {% trans "Point" %} |
          {% blocktrans with month=comment.time|date:"n" day=comment.time|date:"j" time=comment.time|time:"TIME_FORMAT" %}
            {{ month }} Month {{ day }} Day {{ time }}
          {% endblocktrans %}
          </span>
        </div>
        <div class="weui-cell__bd weui-cell_primary">
          <p style="font-size: 13px; padding: 10px 15px;">{{ comment.detail }}</p>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% else %}
<div class="weui-loadmore weui-loadmore_line">
  <span class="weui-loadmore__tips">{% trans "No Comments" %}</span>
</div>
{% endif %}

templates/feedbacks/common.html
{% load i18n %}
<div class="weui-panel weui-panel_access">
  <div class="weui-panel__bd">
    <div class="weui-media-box weui-media-box_appmsg">
      <div class="weui-media-box__hd">
        <img class="weui-media-box__thumb" src="{{ MEDIA_URL }}{{ lecture.speaker.picture }}" alt="">
      </div>
      <div class="weui-media-box__bd">
        <h4 class="weui-media-box__title">{% blocktrans with number=lecture.meeting.number %}The {{ number }} Meeting: {% endblocktrans %}{{ lecture.topic }}</h4>
        <p class="weui-media-box__desc">{{ lecture.speaker.intro }}</p>
        <ul class="weui-media-box__info" style="color: black">
          <li class="weui-media-box__info__meta">
          {% blocktrans with month=lecture.time|date:"n" day=lecture.time|date:"j" time=lecture.time|time:"TIME_FORMAT" %}
          Time: {{ month }} Month {{ day }} Day {{ time }}
          {% endblocktrans %}
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

templates/feedbacks/index.html
{% extends "base.html" %}
{% load i18n %}
{% block js %}
{{ block.super }}
<script>
$("#tabbar-tab0").removeClass("weui-bar__item_on")
$("#tabbar-tab1").removeClass("weui-bar__item_on")
$("#tabbar-tab2").addClass("weui-bar__item_on")
</script>
{% endblock js %}

templates/feedbacks/question.html
{% extends "./index.html" %}
{% load i18n %}
{% block title %}{% trans "Add Question" %}{% endblock title %}

{% block css %}
{{ block.super }}
<style>
#submit-btn {
  border-radius: 0px;
  width: 100%;
}
#submit-btn:after {
  border: 0px;
  border-radius: 0px;
}
</style>
{% endblock css %}

{% block content %}
{% include "./common.html" %}
<form action="{% url 'feedbacks.add_question' lecture.id %}" method="post">
  <div class="weui-panel">
    <div class="weui-panel__bd">
      {% csrf_token %}
      <div class="weui-cell">
        <div class="weui-cell__bd">
          <textarea class="weui-textarea" placeholder="{% trans "Please enter your question: " %}" rows="15" name="detail" id="id_detail" maxlength="200" required></textarea>
        </div>
      </div>
    </div>
  </div>
  <div class="weui-tabbar">
    <input type="submit" class="weui-btn weui-btn_primary" id="submit-btn">
  </div>
</form>
{% endblock content %}

{% block tabbar %}
{% endblock tabbar %}

{% block js %}
{{ block.super }}
<script>
$("form").submit(function(){
  weui.toast("{% trans "Submit Success!" %}", 500);
});
</script>
{% endblock js %}

templates/feedbacks/user_comments.html
{% extends "./index.html" %}
{% load i18n %}
{% block title %}{% trans "My Comments" %}{% endblock title %}

{% block content %}
<div class="weui-panel">
  <div class="weui-panel__bd">
{% for comment in comment_list %}
    <div class="weui-media-box weui-media-box_text">
      <h4 class="weui-media-box__title">
      {% blocktrans with number=comment.lecture.meeting.number speaker_name=comment.lecture.speaker.name %}
      The {{ number }} Meeting: {{ speaker_name }}, {% endblocktrans %}{{ comment.lecture.topic }}
      </h4>
      <p class="weui-media-box__desc">{{ comment.detail }}</p>
      <ul class="weui-media-box__info">
        <li class="weui-media-box__info__meta">{{ comment.time }}</li>
        <li class="weui-media-box__info__meta weui-media-box__info__meta_extra">{{ comment.score }} {% trans "Point" %}</li>
      </ul>
    </div>
{% empty %}
{% endfor %}
  </div>
</div>
{% endblock content %}

templates/feedbacks/user_questions.html
{% extends "./index.html" %}
{% load i18n %}
{% block title %}{% trans "My Questions" %}{% endblock title %}

{% block content %}
<div class="weui-panel">
  <div class="weui-panel__bd">
{% for question in question_list %}
    <div class="weui-media-box weui-media-box_text">
      <h4 class="weui-media-box__title">
      {% blocktrans with number=question.lecture.meeting.number speaker_name=question.lecture.speaker.name %}
      The {{ number }} Meeting: {{ speaker_name }}, {% endblocktrans %}{{ question.lecture.topic }}
      </h4>
      <p class="weui-media-box__desc">{{ question.detail }}</p>
      <ul class="weui-media-box__info">
        <li class="weui-media-box__info__meta">{{ question.time }}</li>
      </ul>
    </div>
{% empty %}
{% endfor %}
  </div>
</div>
{% endblock content %}