live/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^note/$', views.live_note, name='live.live_note'),
    url(r'^add/$', views.add_live, name='live.add_live'),
    url(r'^add/(?P<lecture_id>[0-9]+)/$', views.add_live, name='live.add_live'),
]

nfe/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='lectures.list_categories', permanent=True), name='root'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^feedbacks/', include('feedbacks.urls')),
    url(r'^lectures/', include('lectures.urls')),
    url(r'^live/', include('live.urls')),
    url(r'^profiles/', include('profiles.urls')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lectures/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as _

from utils.utils import upload_speakerimage


class Category(models.Model):
    name = models.CharField(_('Name'), max_length=12)
    order = models.PositiveIntegerField(_('Order'), default=0)

    class Meta:
        ordering = ('order', )
        unique_together = ("name", "order")
        verbose_name = _('Lecture Category')
        verbose_name_plural = _('Lecture Category')

    def __unicode__(self):
        return self.name


class Speaker(models.Model):
    name = models.CharField(_('Speaker Name'), max_length=12, unique=True)
    intro = models.CharField(_('Speaker Info'), max_length=200, blank=True)
    picture = models.ImageField(_('Speaker Picture'),
                                upload_to=upload_speakerimage,
                                blank=True)

    class Meta:
        verbose_name = _('Lecture Speaker')
        verbose_name_plural = _('Lecture Speaker')

    def __unicode__(self):
        return self.name


class Meeting(models.Model):
    number = models.PositiveIntegerField(_('Number'), unique=True)
    name = models.CharField(_('Name'), max_length=12, blank=True)
    time = models.DateTimeField(_('Time'))
    info = models.CharField(_('Info'), max_length=1000, blank=True)
    is_offline = models.BooleanField(_('Is Offline'), default=False)

    class Meta:
        ordering = ('number', )
        verbose_name = _('Meeting Info')
        verbose_name_plural = _('Meeting Info')

    def __unicode__(self):
        return _('{num} Meeting').format(num=self.number)


class Lecture(models.Model):
    order = models.PositiveIntegerField(_('Order'), default=0)
    time = models.DateTimeField(_('Time'))
    topic = models.CharField(_('Topic'), max_length=50)
    info = models.TextField(_('Info'), max_length=500, blank=True)
    url = models.URLField(_('URL'), max_length=300, blank=True)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    speaker = models.ForeignKey('Speaker', on_delete=models.CASCADE)
    meeting = models.ForeignKey('Meeting', on_delete=models.CASCADE)
    is_passed = models.BooleanField(_('Is Passed'), default=True)
    is_finished = models.BooleanField(_('Is Finished'), default=False)

    class Meta:
        ordering = ('order', )
        unique_together = ("topic", "speaker", "meeting")
        verbose_name = _('Lecture Info')
        verbose_name_plural = _('Lecture Info')

    def __unicode__(self):
        return self.topic

live/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as _

from lectures.models import Lecture
from accounts.models import User


class LiveNote(models.Model):
    note = models.CharField(_('Live Note'), max_length=1000)
    is_visible = models.BooleanField(_('Is Visible'), default=True)

    class Meta:
        verbose_name = _('Live Note')
        verbose_name_plural = _('Live Note')

    def __unicode__(self):
        return self.note


class UserLive(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    lecture = models.ForeignKey(Lecture, on_delete=models.CASCADE)
    is_visible = models.BooleanField(_('Is Visible'), default=True)

    class Meta:
        unique_together = ("user", "lecture")
        verbose_name = _('External Live')
        verbose_name_plural = _('External Live')

    def __unicode__(self):
        return '{user} - live'.format(user=self.user)

live/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms
from django.utils.translation import ugettext_lazy as _

from lectures.models import Lecture, Speaker


class LectureForm(forms.ModelForm):
    speaker_name = forms.CharField(label=_('Speaker Name'), max_length=12)
    speaker_intro = forms.CharField(label=_('Speaker Info'), max_length=200)
    speaker_picture = forms.ImageField(label=_('Speaker Picture'), required=False)

    class Meta:
        model = Lecture
        fields = ['topic', 'time', 'info']

live/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import time
import datetime
from django.urls import reverse
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required

from .models import LiveNote, UserLive
from .forms import LectureForm
from accounts.models import User
from lectures.models import Speaker, Category, Meeting, Lecture


def live_note(request):
    user = request.user
    note_list = LiveNote.objects.filter(is_visible=True)
    context = {'note_list': note_list, 'user': user}

    if user.is_authenticated:
        if user.first_name and user.last_name:
            context['certified_user'] = True
            live_list = UserLive.objects.filter(user__id=user.id, is_visible=True)
            context['live_list'] = live_list
            auditing_count = live_list.filter(lecture__is_passed=False).count()
            context['auditing_count'] = auditing_count
    return render(request, 'live/note.html', context=context)

@login_required
def add_live(request, lecture_id=None):
    if request.method == 'POST':
        lecture_form = LectureForm(request.POST, request.FILES)
        t = request.POST['time']
        date = datetime.date.fromtimestamp(time.mktime(time.strptime(t, "%Y-%m-%d")))
        lecture_time = timezone.now().replace(year=date.year, month=date.month, day=date.day)
        topic = request.POST['topic']
        info = request.POST['info']
        speaker_name = request.POST['speaker_name']
        speaker_intro = request.POST['speaker_intro']
        speaker_picture = request.FILES.get('speaker_picture', '')
        category = Category.objects.order_by('order').last()
        meeting = Meeting.objects.order_by('id').first()
        if not lecture_id:
            if speaker_picture:
                speaker = Speaker.objects.create(name=speaker_name, intro=speaker_intro, picture=speaker_picture)
            else:
                speaker = Speaker.objects.create(name=speaker_name, intro=speaker_intro)
            lecture = Lecture.objects.create(topic=topic, speaker=speaker, meeting=meeting,
                                             time=lecture_time, info=info, category=category, is_passed=False)
        else:
            lecture = get_object_or_404(Lecture, id=lecture_id)
            speaker = get_object_or_404(Speaker, id=lecture.speaker.id)
            speaker.name = speaker_name
            speaker.intro = speaker_intro
            if speaker_picture:
                speaker.picture = speaker_picture
            speaker.save()

            lecture.topic = topic
            lecture.time = lecture_time
            lecture.info = info
            lecture.save()
        user = get_object_or_404(User, id=request.user.id)
        UserLive.objects.update_or_create(user=user, lecture=lecture)
        return HttpResponseRedirect(reverse('lectures.list_categories', args=[category.order]))
    else:
        context = {}
        if lecture_id:
            lecture_form = LectureForm()
            lecture = get_object_or_404(Lecture, id=lecture_id)
            context['lecture_id'] = lecture_id
            context['topic'] = lecture.topic
            context['time'] = lecture.time.strftime("%Y-%m-%d")
            context['info'] = lecture.info
            context['speaker_name'] = lecture.speaker.name
            context['speaker_intro'] = lecture.speaker.intro
        else:
            lecture_form = LectureForm()
            user = request.user
            context['speaker_name'] = user.last_name + user.first_name
        context['form'] = lecture_form
        return render(request, 'live/live.html', context=context)

templates/live/index.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Live Note" %}{% endblock title %}
{% block js %}
{{ block.super }}
<script>
$("#tabbar-tab0").removeClass("weui-bar__item_on")
$("#tabbar-tab1").removeClass("weui-bar__item_on")
$("#tabbar-tab2").addClass("weui-bar__item_on")
</script>
{% endblock js %}

templates/live/live.html
{% extends "./index.html" %}
{% load i18n %}
{% block title %}{% trans "Apply Live" %}{% endblock title %}

{% block content %}
{% if lecture_id %}
<form enctype="multipart/form-data" method="post" action="{% url 'live.add_live' lecture_id %}">
{% else %}
<form enctype="multipart/form-data" method="post" action="{% url 'live.add_live' %}">
{% endif %}
  {% csrf_token %}
  <div class="weui-cells__title">{% trans "Please fill in the form below with live info:" %}</div>
  <div class="weui-cells weui-cells_form">
    <div class="weui-cell">
      <div class="weui-cell__hd"><label class="weui-label" for="id_topic">{% trans "Live Topic" %}</label></div>
      <div class="weui-cell__bd">
        <input class="weui-input" type="text" name="topic" value="{{ topic }}" required id="id_topic" maxlength="50" placeholder="{% trans "Live Topic" %}">
      </div>
    </div>
    <div class="weui-cell">
      <div class="weui-cell__hd"><label class="weui-label" for="id_time">{% trans "Appointment Time" %}</label></div>
      <div class="weui-cell__bd">
        <input class="weui-input" type="text" name="time" value="{{ time }}" required id="id_time" placeholder="{% trans "Click here" %}" readonly>
      </div>
    </div>
    <div class="weui-cell">
      <div class="weui-cell__bd">
        <textarea class="weui-textarea" type="text" rows="8" name="info" required id="id_info" maxlength="500" placeholder="{% trans "Please enter the live introduction, less than 500 characters." %}">{{ info }}</textarea>
      </div>
    </div>
  </div>
  <div class="weui-cells__title">{% trans "Please fill in the form below with speaker info:" %}</div>
  <div class="weui-cells weui-cells_form">
    <div class="weui-cell">
      <div class="weui-cell__hd"><label class="weui-label" for="id_speaker_name">{% trans "Speaker Name" %}</label></div>
      <div class="weui-cell__bd">
        <input class="weui-input" type="text" name="speaker_name" value="{{ speaker_name }}" required id="id_speaker_name" maxlength="12" placeholder="{% trans "Speaker Name" %}">
      </div>
    </div>
    <div class="weui-cell">
      <div class="weui-cell__bd">
        <div class="weui-uploader">
          <div class="weui-uploader__hd">
            <p class="weui-uploader__title">{% trans "Speaker Picture" %}</p>
            <div>
              <input type="file" name="speaker_picture" id="id_speaker_picture">
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="weui-cell">
      <div class="weui-cell__bd">
        <textarea class="weui-textarea" type="text" rows="5" name="speaker_intro" required id="id_speaker_intro" maxlength="200" placeholder="{% trans "Please enter the speaker introduction, less than 200 characters." %}">{{ speaker_intro }}</textarea>
      </div>
    </div>
  </div>
  <input type="submit" class="weui-btn weui-btn_primary">
</form>
{% endblock content %}

{% block tabbar %}
{% endblock tabbar %}

{% block js %}
{{ block.super }}
<script>
$("#id_time").click(function(){
  var t = new Date();
  weui.datePicker({
    start: t,
    end: t.getFullYear() + 1,
    defaultValue: [t.getFullYear(), t.getMonth() + 1, t.getDay()],
    onChange: function(result){
      let value = result[0].value + "-" + result[1].value + "-" + result[2].value
      $("#id_time").attr("value", value);
      console.log(result);
    },
    onConfirm: function(result){
      let value = result[0].value + "-" + result[1].value + "-" + result[2].value
      $("#id_time").attr("value", value);
    },
  });
})
</script>
{% endblock js %}

templates/live/note.html
{% extends "./index.html" %}
{% load i18n %}

{% block content %}
{% if auditing_count <= 3 %}
<div class="weui-panel weui-panel_access">
  <div class="weui-panel__hd">{% trans "Apply New Live" %}</div>
  <div class="weui-panel__bd">
    <div class="weui-cell" style="background-color: white;">
      <div class="weui-cell__bd">
        <article class="weui-article">
          <ul>
            {% for note in note_list %}
            <li>{{ note }}</li>
            {% endfor %}
          </ul>
        </article>
        {% if user.is_anonymous %}
        <a href="{% url 'accounts.login' %}" class="weui-btn weui-btn_primary" id="login-btn">{% trans "Please Login and Be Certified" %}</a>
        {% elif user.is_authenticated and not certified_user %}
        <a href="{% url 'accounts.login' %}" class="weui-btn weui-btn_primary" id="login-btn">{% trans "Please Be Certified" %}</a>
        {% elif user.is_authenticated and certified_user %}
        <a href="{% url 'live.add_live' %}" class="weui-btn weui-btn_primary">{% trans "Read and Apply" %}</a>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endif %}
{% if live_list %}
<div class="weui-panel weui-panel_access">
  <div class="weui-panel__hd">{% trans "Live Auditing" %}</div>
  <div class="weui-panel__bd">
  {% for live in live_list %}
    {% if not live.lecture.is_passed %}
    <a href="{% url 'live.add_live' live.lecture.id %}" class="weui-media-box weui-media-box_appmsg">
      <div class="weui-media-box__hd">
        <img class="weui-media-box__thumb" src="{{ MEDIA_URL }}{{ live.lecture.speaker.picture }}" alt="">
      </div>
      <div class="weui-media-box__bd">
        <h4 class="weui-media-box__title">{% blocktrans with number=live.lecture.meeting.number %}The {{ number }} Meeting: {% endblocktrans %}{{ live.lecture.topic }}</h4>
        <p class="weui-media-box__desc">{{ live.lecture.speaker.intro }}</p>
        <ul class="weui-media-box__info" style="color: black">
          <li class="weui-media-box__info__meta">
          {% blocktrans with month=live.lecture.time|date:"n" day=live.lecture.time|date:"j" time=live.lecture.time|time:"TIME_FORMAT" %}
          Time: {{ month }} Month {{ day }} Day {{ time }}
          {% endblocktrans %}
          </li>
        </ul>
      </div>
    </a>
    {% endif %}
  {% empty %}
    <div class="weui-loadmore weui-loadmore_line">
      <span class="weui-loadmore__tips">{% trans "No Live Auditing" %}</span>
    </div>
  {% endfor %}
  </div>
</div>
<div class="weui-panel weui-panel_access">
  <div class="weui-panel__hd">{% trans "Apply Success Records" %}</div>
  <div class="weui-panel__bd">
  {% for live in live_list %}
    {% if live.lecture.is_passed %}
    <div class="weui-media-box weui-media-box_small-appmsg">
      <div class="weui-cells">
        <a class="weui-cell weui-cell_access" href="{% url 'lectures.lecture_detail' live.lecture.id %}">
          <div class="weui-cell__hd"><img src="{{ MEDIA_URL }}{{ live.lecture.speaker.picture }}" alt="" style="width:20px;margin-right:5px;display:block"></div>
          <div class="weui-cell__bd weui-cell_primary">
            <p>
            {% blocktrans with number=live.lecture.meeting.number speaker_name=live.lecture.speaker.name %}
            The {{ number }} Meeting: {{ speaker_name }}, {% endblocktrans %}{{ live.lecture.topic }}
            </p>
          </div>
          <span class="weui-cell__ft"></span>
        </a>
      </div>
    </div>
    {% endif %}
  {% empty %}
    <div class="weui-loadmore weui-loadmore_line">
      <span class="weui-loadmore__tips">{% trans "No Apply Success Records" %}</span>
    </div>
  {% endfor %}
  </div>
</div>
{% endif %}
{% endblock content %}